apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: helm-chart/
    repoURL: 'https://github.com/melihekmekci1/microservices-demo'
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
 
    automated:
      selfHeal: true
      prune: true